<?php

namespace frontend\controllers;

use common\models\Answer;
use common\models\Images;
use common\models\Quize;
use common\models\Quizpractice;
use common\models\Section;
use frontend\components\Helpers\MixPanelHelper;
use Mixpanel;
use stdClass;
use yii;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;

class FreepracticeController extends SiteController
{
    public $tracking = false;

    public function init()
    {
        return parent::init();
    }


    public function actionIndex()
    {
        $this->view->params['title'] = "Sample Q/A";
        $this->view->params['breadcrumbs'] = [
            'links' => [
                'label' => 'Sample Q/A'
            ]
        ];
        return $this->render('index');
    }

    public function actionFinishPractice()
    {
        $session = Yii::$app->session;
        $request = Yii::$app->getRequest()->getBodyParams();

        $quiz_id = $session['quiz_id'];
        $quiz = Quize::findOne($quiz_id);

        foreach ($quiz->questions as $question) {
            if (isset($request['answer'][$question->id])) continue;
            $request['answer'][$question->id] = 0;
        }

        $result = Quizpractice::checkAnswers($request['answer'], null, $quiz_id);

        /* todo
            MixPanel functionality meeds to refactor
         */

        $mp = new MixPanelHelper();
        $mp->track('Anonymous user finish practice');

        return $this->render('result', compact('result', 'quiz'));
    }

    public function actionPractice($id)
    {
        $quiz = Quize::findOne($id);
        if ($quiz && $quiz->subject->examtype->free) {
            $session = Yii::$app->session;
            $session->set('quiz_id', $id);

            $mp = new MixPanelHelper();
            $mp->track('Anonymous user start practice');

            return $this->render('practice', compact('id'));
        } else {
            $previousPage = Yii::$app->request->referrer;
            if (!$previousPage) {
                return $this->redirect('/');
            }
            return $this->redirect($previousPage);
        }
    }

    public function beforeAction($action)
    {
        if(Yii::$app->user->isGuest) {
            $mp = new MixPanelHelper();
            $mp->track('Public page view');
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'finish-practice' => ['post']
                ]
            ]
        ];
    }
}
