<?php

namespace common\models;

use Yii;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "examtype".
 *
 * @property integer $id
 * @property string $name
 * @property integer $free
 */
class Examtype extends ActiveRecord
{
    const EXAM = 2;
    const GRADE_LEVEL = 1;

    public static function find()
    {
        return new ExamtypeQuery(get_called_class());
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'examtype';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'string', 'max' => 255],
            [['schedule'], 'string'],
            [['name'], 'required'],
        ];
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
    }


    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
        ];
    }

    public function getSubjects()
    {
        return $this->hasMany(Subject::className(), ['examtype_id' => 'id']);
    }

    public static function getCaption()
    {

    }

    public function checkOwner()
    {
        return $this->user_id == Yii::$app->user->identity->id;
    }

    public function isFree()
    {
        return $this->free ? true : false;
    }
}

class ExamtypeQuery extends ActiveQuery
{
    // ...
}