<?php
namespace frontend\models;

use common\models\Student;
use common\models\SystemSetting;
use common\models\Tutor;
use frontend\components\Helpers\MixPanelHelper;
use Yii;
use yii\base\Model;
use common\models\User;

/**
 * UserSignupForm model
 * @property string $firstName
 * @property string $lastName
 * @property date $dateOfBirth
 * @property integer $sex
 * @property integer $userType
 */
class UserSignupForm extends Model
{
    public $firstName;
    public $lastName;
    public $sex = 1;
    public $dateOfBirth;
    public $email;
    public $social_id;

    public $userType;

    public $userTypes = [
        '1' => 'Student',
        '2' => 'Tutor'
    ];

    public $sexs = [
        '1' => 'Male',
        '0' => 'Female'
    ];

    public function init()
    {
        if(SystemSetting::payment_enabled()) {
            $this->userTypes = [
                '1' => 'Student',
                '2' => 'Tutor'
            ];
        }
        parent::init(); // TODO: Change the autogenerated stub
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['firstName', 'lastName'], 'filter', 'filter' => 'trim'],
            [['firstName', 'lastName', 'userType', 'email'], 'required'],
            [['firstName', 'lastName'], 'string', 'max' => 50],
            ['email', 'email'],
            ['email', 'unique', 'targetClass' => '\common\models\User', 'message' => 'This email has already been taken.'],
            [['sex'], 'boolean'],
            [['social_id'], 'string'],
            ['dateOfBirth', 'date', 'format' => 'dd-M-yyyy'],
        ];
    }

    public function scenarios()
    {
        $scenarios = parent::scenarios();
        $scenarios['student-scenario'] = ['sex', 'dateOfBirth'];
        return $scenarios;
    }

    public function signUpUser()
    {
        $user = new User();
        $user->first_name = $this->firstName;
        $user->last_name = $this->lastName;
        $user->sex = $this->sex;

        if (!empty($this->dateOfBirth)) {
            $user->date_birth = date('Y-m-d', strtotime($this->dateOfBirth));
        }
        $user->user_type = $this->userType;
        $user->email = $this->email;

        $user->social_id = $this->social_id ? $this->social_id : null;

        $user->generateAuthKey();

        $user->setPassword(Yii::$app->security->generateRandomString());
        $user->generatePasswordResetToken();

        if ($user->save()) {

            $auth = Yii::$app->authManager;

            $mp = new MixPanelHelper($user);
            $mp->setAlias()->track('Registered');

            switch ($user->user_type) {
                case User::TYPE_STUDENT:
                    $auth->assign($auth->getRole('student'), $user->id);
                    $student = new Student();
                    $student->user_id = $user->id;
                    $student->load($user->toArray(), '');
                    $student->save();
                    break;
                case User::TYPE_TEACHER:
                    $auth->assign($auth->getRole('teacher'), $user->id);
                    $tutor = new Tutor();
                    $tutor->user_id = $user->id;
                    $tutor->load($user->toArray(), '');
                    $tutor->save();
                    break;
                default:
            }

            if (!empty($user->email)) {
                $this->sendEmail($user);
            }
            return Yii::$app->user->login($user, 3600 * 24 * 30);
        };
    }


    private function sendEmail($user)
    {
        if (empty($user->social_id)) {
            $status = Yii::$app->mailer->compose(['html' => 'confirmationEmail'], ['user' => $user])
                ->setFrom([Yii::$app->components['mailer']['transport']['username'] => 'Training/Learning Application'])
                ->setTo($user->email)
                ->setSubject('Welcome to Training/Learning Application')
                ->send();
            if ($status) {
                Yii::$app->session->setFlash('success', 'Check your Email and follow the link to set password for your account');
            }
        }
    }
}
